spring.application.name=gestion-fabrication

# Server
server.port=${PORT:8080}
server.address=0.0.0.0

# Cloud SQL (Socket Factory)
spring.datasource.url=jdbc:mysql:///fabricationdb?cloudSqlInstance=gestion-fabrication-496611:europe-west1:fabrication-db&socketFactory=com.google.cloud.sql.mysql.SocketFactory&useSSL=false
spring.datasource.username=${DB_USER:fabrication}
spring.datasource.password=${DB_PASSWORD:fabrication123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Connection pool
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html